### ISSUE TITLE
More context on how to hide markdown editor

### ISSUE THREAD

**Issue by mneumegen** [CloudCannon/platform-documentation#10]
I was looking around the docs on how to hide the content editor and ended up asking in #support. I was expecting to find an answer in the two spots below. A small tip or sentence pointing me in the right direction would have meant I could solve my problem on my own.

<img width="1059" alt="Screen Shot 2023-03-13 at 1 18 49 PM" src="https://user-images.githubusercontent.com/312386/225702018-b1202acd-a03f-41b5-8e2e-dc0bd79f49e4.png">
<img width="1064" alt="Screen Shot 2023-03-13 at 1 19 01 PM" src="https://user-images.githubusercontent.com/312386/225702058-f6bd9aa9-8824-4794-8d62-dce504d7f546.png">

**Comment by rphillips-cc** [comment]
Completed in https://github.com/CloudCannon/platform-documentation/pull/88
