### ISSUE TITLE
Can I include this page in the Lume's showcase?

### ISSUE THREAD

**Issue by oscarotero** [CloudCannon/platform-documentation#142]
Hi, I was reading the cloudcannon documentation and just realized it's built with Lume 🎉 

Are you okay if I include it in the Showcase section of Lume site? https://lume.land/showcase/

BTW, let me know if you find any issues or need help with anything (I'm the Lume creator).
Thanks!

**Comment by bglw** [comment]
Hey @oscarotero 👋 

Of course! I meant to flick it through at some point but I forgot 🫣 

I'll keep in touch — you've already [helped](https://github.com/lumeland/lume/pull/394) us [solve](https://github.com/lumeland/lume/pull/388) some [things](https://github.com/lumeland/lume/issues/375)! 😄 ❤️
