### ISSUE TITLE
Mentioning all our supported DAMS on the "Introduction to Assets and DAMs" page

### ISSUE THREAD

**Issue by cpw10** [CloudCannon/platform-documentation#161]
Hey gang,

Can we update https://cloudcannon.com/documentation/articles/introduction-to-assets-and-dams/ to mention DigitalOcean and Cloudflare DAMs, please?

Thank you 🙏 

![Screen Shot 2023-09-26 at 10 52 53 AM](https://github.com/CloudCannon/platform-documentation/assets/109151605/0164ee00-75c2-4dec-bb6b-1154bdbb77be)

**Comment by EllaCloudCannon** [comment]
Hi Chris,

This issue is resolved.

Ella
