### ISSUE TITLE
Update Default Hugo Version

### ISSUE THREAD

**Issue by m-mok-cc** [CloudCannon/platform-documentation#164]
[Setting your SSG version](https://cloudcannon.com/documentation/articles/configuring-your-build/#setting-your-ssg-version) for Hugo should be updated to show the new default as 0.118.2. It is currently showing as 0.96.0_extended.

**Comment by EllaCloudCannon** [comment]
Hi m-mok-cc,
Our documentation has been updated appropriately.
Ella
