### ISSUE TITLE
More examples for automated scheduled builds

### ISSUE THREAD

**Issue by mneumegen** [CloudCannon/platform-documentation#17]
I was trying to set up an [automated scheduled build ](https://cloudcannon.com/documentation/articles/scheduling-your-next-build-automatically/) on an 11ty site and wasn't sure the best way to implement it. The docs showed me what the output should look like but I wasn't sure the best way to implement it. 

Once I came across the [CloudCannon Jekyll plugin](https://github.com/CloudCannon/jekyll-cloudcannon-schedule/blob/master/lib/_schedule.txt), I realized how simple it was and had no problems implementing it. 

Having some pesudo code, or SSG-specific examples would help make this setup easier.

Now I'm wondering, where do I generate this file? Is it in the root directory, src directory, or does it just need to be in the root of the output site?

I'm also not sure what format the date should be in.

**Comment by rycoll** [comment]
Fixed in PR #33
