### ISSUE TITLE
Structures and Arrays documentation

### ISSUE THREAD

**Issue by cpw10** [CloudCannon/platform-documentation#212]
I'm doing some upskilling with Delaney and was reading through our Structures/Arrays documentation. I find the structure (no pun intended) of the articles a bit confusing. When clicking "Structures" in the navigation, the first page I land on is a page called "Defining what adds to an array". And the first sentence in this article is "By default, arrays in the Data Editor allow you to create new items". 

We eventually get to Structures and have examples, but I'm not sure it's the most intuitive. I'm not a developer, so I'm maybe not the perfect audience. Is there room to have a section where we define Structures as a concept in CloudCannon a bit more clearly? I also understand that Arrays is a common computer science/software engineer term and that we have this section: https://cloudcannon.com/documentation/articles/using-arrays-to-edit-your-data/#array. But it all seems a bit back and forth.

If a customer comes to us and wants to create a component-based editing experience using Next.js. They don't want to use Bookshop. Aside from the guide (I think it's easier to understand in: https://cloudcannon.com/documentation/guides/nextjs-starter-guide/collection-configuration/). What specific articles do we send them? And in what order to we send it to them?

Appreciate any insights, thanks team

**Comment by EllaCloudCannon** [comment]
Hi Chris,

An introductory page for Structures is on my to-do list for the new year.
This area of the docs has been earmarked for a complete restructure (no pun intended).

I'll flick you a message when this project is underway!

Ella

**Comment by EllaCloudCannon** [comment]
Hi Chris,

The new Structures documentation went out today!

Ella
