### ISSUE TITLE
Best practices guide for Hugo i18n

### ISSUE THREAD

**Issue by rycoll** [CloudCannon/platform-documentation#43]
We don't have any specific guide for Hugo i18n, but in general it will work as is. If we did write a guide/blog post I would suggest we cover the two ways to specify language-specific versions of pages in Hugo. Here are the first steps for each one might take to improve the in-app experience:

1. A folder per language (e.g. `content/posts/es/my-post.md`):
- Create a collection per language/content type (e.g. "Posts EN" with `path: content/posts/en`, and "Posts ES" with `path: content/posts/es`)
2. A language per file (e.g. `content/posts/my-post.es.md`):
- Use Create Paths to allow editors to choose the language code when saving a new file (see example below).

`cloudcannon.config.yml`:

```
collections_config:
  posts:
    create: '{title|slugify}.{language|lowercase}.md'
```

**Comment by rphillips-cc** [comment]
Completed on https://cloudcannon.com/documentation/guides/hugo-multilingual/
