### ISSUE TITLE
Incomplete HTML and markdown input docs

### ISSUE THREAD

**Issue by tomrcc** [CloudCannon/platform-documentation#44]
[This ](https://cloudcannon.com/documentation/articles/using-rich-text-inputs-to-edit-your-data/#valid-values) last part of this page looks incomplete. No valid values, related articles or related links are listed, resulting in some empty headings at the end of the page.

**Comment by rphillips-cc** [comment]
Duplicate of https://github.com/CloudCannon/platform-documentation/issues/29
