### ISSUE TITLE
Guide for migrating i18n to Rosey

### ISSUE THREAD

**Issue by rycoll** [CloudCannon/platform-documentation#58]
Sometimes users need i18n functionality beyond the scope of CloudCannon's built-in i18n feature (e.g. translating attributes of 
HTML elements). In these cases, we might suggest they switch over to using Rosey - it would be nice to have a good guide on hand to support them through that process. 

I've attached a file that covers pretty much everything you need to do in this migration process.

However, there are some additional caveats we need to add. Using Rosey in the postbuild messes with the Visual Editor (since it moves the built files around), so you really need a staging/production workflow to make this viable at all. We would probably want to explain this, and maybe link out to another guide about staging/production workflows.

[migrating-i18n-to-rosey.md](https://github.com/CloudCannon/platform-documentation/files/11436815/migrating-i18n-to-rosey.md)

**Comment by rphillips-cc** [comment]
Staging workflow guide now completed with https://github.com/CloudCannon/platform-documentation/pull/94
