### ISSUE TITLE
Update inputs screenshots

### ISSUE THREAD

**Issue by rycoll** [CloudCannon/platform-documentation#73]
Do a sweep of all our [inputs](https://cloudcannon.com/documentation/articles/how-to-choose-what-input-is-used-in-the-data-editor/) screenshots and make sure they're up-to-date.

**Comment by NJKode** [comment]
Is [this PR](https://github.com/CloudCannon/platform-documentation/pull/85) (merged a month ago) sufficient to close this issue?

All inputs (excluding Objects) had their screenshots updated.

**Comment by NJKode** [comment]
I'm gonna say yes.
